name: Flutter CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: dart pub get
      - run: dart run melos bootstrap
      - run: dart run melos run analyze
      - run: dart run melos run test
